version: "3.9"
services:
  postgresdb:
    image: postgres
    container_name: postgresdb
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres-db:/data/postgres

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: user@postgres.com
      PGADMIN_DEFAULT_PASSWORD: password
    volumes:
      - pgadmin-data:/data/postgres

volumes:
  postgres-db:
    driver: local
  pgadmin-data:
    driver: local